name: Run Code Analyzer IS
description: Action to install and run custom-made code analyzer dotnet tool.
branding:
    icon: 'code'
    color: 'orange'
        
runs:
    using: "composite"
    steps:
        - name: Install .NET Core SDK
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '7.0'
        - name: Install code analyzer dotnet tool
          run: dotnet tool install --global CATPluginExperimentISTest
          shell: bash
        - name: Run code analyzer dotnet tool
          run: csharp_analyzer_IS
          shell: bash
