name: Code Analyzer Tool Action
description: Action to install and run custom-made code analyzer tool.
branding:
    icon: 'code'
    color: 'orange'
        
runs:
    using: "composite"
    steps:
        - name: Install .NET Core SDK
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '7.0'
        - name: Install code analyzer tool
          run: dotnet tool install --global CodeAnalyzerTool
          shell: bash
        - name: Run code analyzer tool
          run: code_analyzer_tool
          shell: bash
